/* 
 *
 * IVE - Inteligent Virtual Environment
 * Copyright (c) 2005-2009, IVE Team, Charles University in Prague
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 * are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice, 
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, 
 *       this list of conditions and the following disclaimer in the documentation 
 *       and/or other materials provided with the distribution.
 *     * Neither the name of the Charles University nor the names of its contributors 
 *       may be used to endorse or promote products derived from this software 
 *       without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
 * OF SUCH DAMAGE.
 *
 */
 
package cz.ive.evaltree.dependentnodes;


/* Generated by Together */


import cz.ive.evaltree.valueholdersimpl.ValueHolderImpl;
import java.util.List;

import java.util.Queue;
import cz.ive.messaging.*;
import cz.ive.process.Substitution;
import cz.ive.evaltree.*;
import cz.ive.sensors.Sensor;


/**
 * Succesor of all nodes that depends on another object than Expr succesor
 * like Source, attribute , MOS 
 */
public abstract class GenericHookDependentNode<TYPE extends ValueHolderImpl> 
        extends DependentNode<TYPE, ValueHolderImpl> {
    
    /**
     * @return 0
     */
    public int getNumberOfChildren() {
        return 0;
    }
    
    /**
     * @return null
     */
    public Expr<ValueHolderImpl, ? extends ValueHolderImpl> getChild(int i) {
        return  null;
    }
    
    /**
     * @return false
     */
    public boolean remapChild(
            Expr<ValueHolderImpl, ? extends ValueHolderImpl> old,
            Expr<ValueHolderImpl, ? extends ValueHolderImpl> n) {
        return false;
    }    
}
