/* 
 *
 * IVE Editor 
 * Copyright (c) 2005-2009, IVE Team, Charles University in Prague
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 * are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice, 
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, 
 *       this list of conditions and the following disclaimer in the documentation 
 *       and/or other materials provided with the distribution.
 *     * Neither the name of the Charles University nor the names of its contributors 
 *       may be used to endorse or promote products derived from this software 
 *       without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
 * OF SUCH DAMAGE.
 *
 */
 
package IVE_Editor.Design;

/**
 *
 * @author  Jirka
 */
public class GraphicManagerWindow extends javax.swing.JFrame
{
    
    /** Creates new form GraphicManagerWindow */
    public GraphicManagerWindow()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        panelEdit = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelTemplatesCtrl = new javax.swing.JPanel();
        buttonNewTepmlate = new javax.swing.JButton();
        buttonDeleteTemplate = new javax.swing.JButton();
        panelTemplateRight = new javax.swing.JPanel();
        labelGraphicTemplates = new javax.swing.JLabel();
        scrollPaneTemplates = new javax.swing.JScrollPane();
        panelGraphicTemplatesContainer = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonNewFrame = new javax.swing.JButton();
        buttonDeleteFrame = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelFramesLabels = new javax.swing.JPanel();
        labelFramesCaption = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelFramesColon = new javax.swing.JLabel();
        scrollPaneFrames = new javax.swing.JScrollPane();
        panelFramesContainer = new javax.swing.JPanel();
        panelCtrlButtons = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        panelEdit.setLayout(new java.awt.GridLayout(2, 0));

        panelEdit.setAlignmentX(0.0F);
        panelEdit.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setAlignmentX(0.0F);
        panelTemplatesCtrl.setLayout(new javax.swing.BoxLayout(panelTemplatesCtrl, javax.swing.BoxLayout.Y_AXIS));

        panelTemplatesCtrl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTemplatesCtrl.setAlignmentY(0.0F);
        panelTemplatesCtrl.setMaximumSize(new java.awt.Dimension(77, 32767));
        buttonNewTepmlate.setText("New");
        buttonNewTepmlate.setToolTipText("Creates a new template");
        panelTemplatesCtrl.add(buttonNewTepmlate);

        buttonDeleteTemplate.setText("Delete");
        buttonDeleteTemplate.setToolTipText("Deletes chosen actually template");
        panelTemplatesCtrl.add(buttonDeleteTemplate);

        jPanel1.add(panelTemplatesCtrl);

        panelTemplateRight.setLayout(new javax.swing.BoxLayout(panelTemplateRight, javax.swing.BoxLayout.Y_AXIS));

        panelTemplateRight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTemplateRight.setAlignmentX(0.0F);
        panelTemplateRight.setAlignmentY(0.0F);
        labelGraphicTemplates.setText("Graphic templates:");
        labelGraphicTemplates.setAlignmentY(0.0F);
        panelTemplateRight.add(labelGraphicTemplates);

        scrollPaneTemplates.setAlignmentX(0.0F);
        panelGraphicTemplatesContainer.setLayout(new javax.swing.BoxLayout(panelGraphicTemplatesContainer, javax.swing.BoxLayout.Y_AXIS));

        scrollPaneTemplates.setViewportView(panelGraphicTemplatesContainer);

        panelTemplateRight.add(scrollPaneTemplates);

        jPanel1.add(panelTemplateRight);

        panelEdit.add(jPanel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMaximumSize(new java.awt.Dimension(77, 32767));
        buttonNewFrame.setText("New");
        buttonNewFrame.setToolTipText("Creates a new Frame in chosen template");
        buttonNewFrame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonNewFrameActionPerformed(evt);
            }
        });

        jPanel2.add(buttonNewFrame);

        buttonDeleteFrame.setText("Delete");
        buttonDeleteFrame.setToolTipText("Deltes a chosen frame");
        jPanel2.add(buttonDeleteFrame);

        jPanel4.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setAlignmentY(0.0F);
        panelFramesLabels.setLayout(new javax.swing.BoxLayout(panelFramesLabels, javax.swing.BoxLayout.X_AXIS));

        panelFramesLabels.setAlignmentX(0.0F);
        labelFramesCaption.setText("Frames of graphic template ");
        panelFramesLabels.add(labelFramesCaption);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 12));
        jLabel1.setText("name of Template");
        panelFramesLabels.add(jLabel1);

        labelFramesColon.setText(":");
        panelFramesLabels.add(labelFramesColon);

        jPanel3.add(panelFramesLabels);

        scrollPaneFrames.setAlignmentX(0.0F);
        panelFramesContainer.setLayout(new javax.swing.BoxLayout(panelFramesContainer, javax.swing.BoxLayout.Y_AXIS));

        scrollPaneFrames.setViewportView(panelFramesContainer);

        jPanel3.add(scrollPaneFrames);

        jPanel4.add(jPanel3);

        panelEdit.add(jPanel4);

        getContentPane().add(panelEdit);

        panelCtrlButtons.setLayout(new javax.swing.BoxLayout(panelCtrlButtons, javax.swing.BoxLayout.X_AXIS));

        panelCtrlButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCtrlButtons.setAlignmentX(0.0F);
        panelCtrlButtons.setAlignmentY(0.0F);
        panelCtrlButtons.setMaximumSize(new java.awt.Dimension(32767, 27));
        cancelButton.setText("Close");
        panelCtrlButtons.add(cancelButton);

        okButton.setText("OK");
        panelCtrlButtons.add(okButton);

        getContentPane().add(panelCtrlButtons);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewFrameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonNewFrameActionPerformed
    {//GEN-HEADEREND:event_buttonNewFrameActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_buttonNewFrameActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GraphicManagerWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteFrame;
    private javax.swing.JButton buttonDeleteTemplate;
    private javax.swing.JButton buttonNewFrame;
    private javax.swing.JButton buttonNewTepmlate;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelFramesCaption;
    private javax.swing.JLabel labelFramesColon;
    private javax.swing.JLabel labelGraphicTemplates;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelCtrlButtons;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelFramesContainer;
    private javax.swing.JPanel panelFramesLabels;
    private javax.swing.JPanel panelGraphicTemplatesContainer;
    private javax.swing.JPanel panelTemplateRight;
    private javax.swing.JPanel panelTemplatesCtrl;
    private javax.swing.JScrollPane scrollPaneFrames;
    private javax.swing.JScrollPane scrollPaneTemplates;
    // End of variables declaration//GEN-END:variables
    
}
